---
title: "Untitled"
author: "_"
date: "2023-01-31"
output: html_document
---

### Import packages
```{r setup, include=FALSE}
install.packages("opusminer")
install.packages("arulesViz")
library("opusminer")
library("arules")
library("ggplot2")
library("arulesViz")
setwd("~/IODAA/Cours_IODAA/Fil_rouge/test_opusm")
df <- read.csv("data_categorielle_opus_new.csv", sep=";")
```

## Exploration du dataset

```{r}
trans = read_transactions("data_categorielle_opus_new.csv", sep = ";", format = "transactions") 
#summary(trans)
```



## Extraire des rules : 
## Algorithme utilisé = APRIORI
```{r setup, include=FALSE}
df[,1]=as.factor(df[,1])
df[,2]=as.factor(df[,2])
df[,3]=as.factor(df[,3])
df[,4]=as.factor(df[,4])
df[,5]=as.factor(df[,5])
df[,6]=as.factor(df[,6])
df[,7]=as.factor(df[,7])
df[,8]=as.factor(df[,8])
df[,9]=as.factor(df[,9])
df[,10]=as.factor(df[,10])
rules<- apriori(df, parameter = list(supp = 0.1, conf = 0.6, target = "rules"))
rules
```

```{r}
summary(rules)
inspect(head(rules, n = 10, by = "lift"))
```
```{r}
df[,1]=as.factor(df[,1])
df[,2]=as.factor(df[,2])
df[,3]=as.factor(df[,3])
df[,4]=as.factor(df[,4])
df[,5]=as.factor(df[,5])
df[,6]=as.factor(df[,6])
df[,7]=as.factor(df[,7])
df[,8]=as.factor(df[,8])
df[,9]=as.factor(df[,9])
df[,10]=as.factor(df[,10])
freqitems<- apriori(df, parameter = list(target = "frequent"))
summary(freqitems)
sortfreqitems=sort(freqitems, decreasing=TRUE, by="support")
inspect(sortfreqitems[0:100])
```

### Générer les motifs fréquents 


```{r}
itemset <- unique(generatingItemsets(rules))
itemset
itemset.df <- as(itemset, "data.frame")
frequentItemset <- itemset.df[with(itemset.df, order(-support, items)),]
names(frequentItemset)[1] <- "itemset"
head(frequentItemset)
```

```{r}
opus(trans, k = 100, print_closures = FALSE, filter_itemsets = TRUE, search_by_lift = FALSE, correct_for_mult_compare = TRUE, redundancy_tests = TRUE)
```
